/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/assets/models/airplane.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { Matrix4, Quaternion, Vector3 } from 'three';
import { updatePlaneAxis, isMenuOpen } from './controls';
import { cameraRotationOffset } from './CameraDragControls';

const x = new Vector3(1, 0, 0);
const y = new Vector3(0, 1, 0);
const z = new Vector3(0, 0, 1);
// Terrain size: 3455m * 0.01 scale = 34.55 units
// North border is at +terrainSize/2 (north is positive Z in this coordinate system)
const terrainSize = 34.55;
const northBorderZ = terrainSize / 2; // +17.275
export const planePosition = new Vector3(0, 3, northBorderZ);

const delayedRotMatrix = new Matrix4();
const delayedQuaternion = new Quaternion();

export function Airplane(props) {
  // thanks to:
  // https://sketchfab.com/3d-models/vintage-toy-airplane-7de2ecbc0acb4b1886c3df3d196c366b
  const { nodes, materials } = useGLTF('assets/models/airplane.glb');
  const groupRef = useRef();
  const helixMeshRef = useRef();

  useFrame(({ camera }) => {
    updatePlaneAxis(x, y, z, planePosition, camera);

    const rotMatrix = new Matrix4().makeBasis(x, y, z);

    const matrix = new Matrix4()
    .multiply(new Matrix4().makeTranslation(planePosition.x, planePosition.y, planePosition.z))
    .multiply(rotMatrix);

    groupRef.current.matrixAutoUpdate = false;
    groupRef.current.matrix.copy(matrix);
    groupRef.current.matrixWorldNeedsUpdate = true;


    var quaternionA = new Quaternion().copy(delayedQuaternion);

    // warning! setting the quaternion from the rotation matrix will cause
    // issues that resemble gimbal locks, instead, always use the quaternion notation
    // throughout the slerping phase
    // quaternionA.setFromRotationMatrix(delayedRotMatrix);

    var quaternionB = new Quaternion();
    quaternionB.setFromRotationMatrix(rotMatrix);

    var interpolationFactor = 0.175;
    var interpolatedQuaternion = new Quaternion().copy(quaternionA);
    interpolatedQuaternion.slerp(quaternionB, interpolationFactor);
    delayedQuaternion.copy(interpolatedQuaternion);

    delayedRotMatrix.identity();
    delayedRotMatrix.makeRotationFromQuaternion(delayedQuaternion);

    // Base camera offset relative to airplane (behind and slightly above)
    // This is the default position when no drag rotation is applied
    const baseCameraOffset = new Vector3(0, 0.015, 0.3);
    
    // Apply the airplane's rotation to the base offset
    // This makes the camera follow behind the airplane
    const rotatedOffset = baseCameraOffset.clone();
    rotatedOffset.applyMatrix4(delayedRotMatrix);
    
    // Apply additional rotation for the slight downward angle
    const downAngle = new Matrix4().makeRotationX(-0.2);
    rotatedOffset.applyMatrix4(downAngle);
    
    // Now apply drag rotation offsets to orbit around the airplane
    // Start with the rotated offset
    let finalOffset = rotatedOffset.clone();
    
    if (cameraRotationOffset.yaw !== 0 || cameraRotationOffset.pitch !== 0) {
      // Get the airplane's up vector (world Y or airplane's Y)
      const planeUp = new Vector3(0, 1, 0);
      planeUp.applyMatrix4(delayedRotMatrix);
      planeUp.normalize();
      
      // Get the airplane's forward vector (negative Z in airplane space)
      const planeForward = new Vector3(0, 0, -1);
      planeForward.applyMatrix4(delayedRotMatrix);
      planeForward.normalize();
      
      // Get the airplane's right vector
      const planeRight = new Vector3(1, 0, 0);
      planeRight.applyMatrix4(delayedRotMatrix);
      planeRight.normalize();
      
      // Apply yaw rotation around the airplane's up vector
      const yawQuaternion = new Quaternion().setFromAxisAngle(planeUp, cameraRotationOffset.yaw);
      finalOffset.applyQuaternion(yawQuaternion);
      
      // Apply pitch rotation around the airplane's right vector
      const pitchQuaternion = new Quaternion().setFromAxisAngle(planeRight, cameraRotationOffset.pitch);
      finalOffset.applyQuaternion(pitchQuaternion);
    }
    
    // Calculate final camera position: airplane position + offset
    const cameraPosition = planePosition.clone().add(finalOffset);
    
    // Calculate look-at target: slightly forward from airplane position along its forward direction
    // This keeps the airplane centered in view
    const lookAtOffset = new Vector3(0, 0, -0.15); // Slightly forward along airplane's forward
    lookAtOffset.applyMatrix4(delayedRotMatrix);
    const lookAtTarget = planePosition.clone().add(lookAtOffset);
    
    // Calculate the forward direction (from camera to target)
    const forward = lookAtTarget.clone().sub(cameraPosition).normalize();
    
    // Calculate right vector (cross product of forward and world up)
    const worldUp = new Vector3(0, 1, 0);
    let right = new Vector3().crossVectors(forward, worldUp).normalize();
    
    // Handle edge case where forward is parallel to world up
    if (right.length() < 0.01) {
      right = new Vector3(1, 0, 0);
    }
    
    // Calculate the actual up vector (perpendicular to both forward and right)
    const up = new Vector3().crossVectors(right, forward).normalize();
    
    // Build camera matrix: position + orientation (right, up, -forward)
    // Note: camera looks down -Z, so we use -forward
    const cameraMatrix = new Matrix4();
    cameraMatrix.makeBasis(right, up, forward.clone().negate());
    
    // Set the position (makeBasis only sets orientation, position defaults to 0,0,0)
    cameraMatrix.setPosition(cameraPosition);

    camera.matrixAutoUpdate = false;
    camera.matrix.copy(cameraMatrix);
    camera.matrixWorldNeedsUpdate = true;

    // Only rotate helix when menu is not open
    if (!isMenuOpen && helixMeshRef.current) {
      helixMeshRef.current.rotation.z -= 1.0;
    }
  });

  return (
    <>
      <group ref={groupRef}>
        <group {...props} dispose={null} scale={0.01} rotation-y={Math.PI}>
          <mesh geometry={nodes.supports.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.chassis.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.helix.geometry} material={materials['Material.005']} ref={helixMeshRef} />
        </group>
      </group>
    </>
  )
}

useGLTF.preload('assets/models/airplane.glb');
